apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
