apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-productivity
        namespace: productivity
  values:
    controllers:
      it-tools:
        containers:
          app:
            image:
              repository: sharevb/it-tools
              tag: "2026.1.4"
    service:
      app:
        controller: it-tools
        ports:
          http:
            port: 8080
