apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  namespace: authentik
  annotations:
    cnpg.io/pvc-owner-group: '26'
spec:
  instances: 3

  storage:
    size: 10Gi
    storageClass: "longhorn"

  ephemeralVolumeSource: {}

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
