apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - secrets.yaml
  - database.yaml
  - release.yaml
  - ingress.yaml
  - networkpolicy.yaml
