apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: authentik
      version: "2025.6.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secret-key
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
      optional: false

    - kind: Secret
      name: authentik-database-app
      valuesKey: password
      targetPath: authentik.postgresql.password
      optional: true

  values:
    server:
      service:
        main:
          enabled: true
          type: ClusterIP
          ports:
            http:
              port: 80
              targetPort: 9000
              protocol: TCP

    authentik:
      env:
        - name: AUTHENTIK_HOST
          value: https://sso.zech.dev

      error_reporting:
        enabled: true

      postgresql:
        host: authentik-database-rw.authentik.svc.cluster.local
        user: authentik
        database: authentik

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

    postgresql:
      enabled: false

    redis:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
