apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-cloud-data-pvc
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: "nfs"
  volumeName: nfs-cloud-data
