apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-immich-photos-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: "nfs"
  volumeName: nfs-immich-photos
