apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: "nfs"
  volumeName: nfs-media-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-tv-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: "nfs"
  volumeName: nfs-media-tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-movies-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: "nfs"
  volumeName: nfs-media-movies
