apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tracearr-secrets
  namespace: media
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Tracearr"
  managedKubeSecretReferences:
    - secretName: tracearr-secrets
      secretNamespace: media
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          JWT_SECRET: "{{ .JWT_SECRET.Value }}"
          COOKIE_SECRET: "{{ .COOKIE_SECRET.Value }}"
