apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tracearr-redis
  namespace: media
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      tracearr-redis:
        containers:
          app:
            image:
              repository: redis
              tag: "8.6.1-alpine"
            command:
              - redis-server
              - --appendonly
              - "yes"
    service:
      app:
        controller: tracearr-redis
        ports:
          redis:
            port: 6379
    persistence:
      data:
        enabled: true
        existingClaim: tracearr-redis-pvc
        globalMounts:
          - path: /data
