apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tracearr
  namespace: media
spec:
  interval: 15m
  timeout: 15m
  dependsOn:
    - name: tracearr-redis
      namespace: media
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      tracearr:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/connorgallopo/tracearr
              tag: "1.4.18"
            env:
              - name: NODE_ENV
                value: production
              - name: PORT
                value: "3000"
              - name: HOST
                value: 0.0.0.0
              - name: TZ
                value: Europe/Vienna
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: tracearr-database-app
                    key: uri
              - name: REDIS_URL
                value: redis://tracearr-redis.media.svc.cluster.local:6379
              - name: JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: tracearr-secrets
                    key: JWT_SECRET
              - name: COOKIE_SECRET
                valueFrom:
                  secretKeyRef:
                    name: tracearr-secrets
                    key: COOKIE_SECRET
              - name: CORS_ORIGIN
                value: https://tracearr.${DOMAIN}
              - name: LOG_LEVEL
                value: info
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: "1"
                memory: 1Gi
    service:
      app:
        controller: tracearr
        ports:
          http:
            port: 3000
