apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: teslamate-secrets
  namespace: productivity
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Teslamate"
  managedKubeSecretReferences:
    - secretName: teslamate-secrets
      secretNamespace: productivity
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY.Value }}"
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GF_AUTH_GENERIC_OAUTH_CLIENT_ID.Value }}"
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET.Value }}"
