apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate-grafana
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-productivity
        namespace: productivity
  values:
    controllers:
      teslamate-grafana:
        pod:
          securityContext:
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
        containers:
          app:
            image:
              repository: teslamate/grafana
              tag: "2.2.0"
            securityContext:
              runAsUser: 472
              runAsGroup: 472
              runAsNonRoot: true
            env:
              - name: DATABASE_HOST
                value: teslamate-database-rw.productivity.svc.cluster.local
              - name: DATABASE_NAME
                value: teslamate
              - name: DATABASE_USER
                value: teslamate
              - name: DATABASE_PASS
                valueFrom:
                  secretKeyRef:
                    name: teslamate-database-app
                    key: password
              - name: GF_SERVER_ROOT_URL
                value: https://teslamate-grafana.${DOMAIN}
              - name: GF_AUTH_GENERIC_OAUTH_ENABLED
                value: "true"
              - name: GF_AUTH_GENERIC_OAUTH_NAME
                value: Authentik
              - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: teslamate-secrets
                    key: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: teslamate-secrets
                    key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              - name: GF_AUTH_GENERIC_OAUTH_SCOPES
                value: openid profile email
              - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
                value: https://sso.${DOMAIN}/application/o/authorize/
              - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
                value: https://sso.${DOMAIN}/application/o/token/
              - name: GF_AUTH_GENERIC_OAUTH_API_URL
                value: https://sso.${DOMAIN}/application/o/userinfo/
              - name: GF_AUTH_SIGNOUT_REDIRECT_URL
                value: https://sso.${DOMAIN}/application/o/teslamate-grafana/end-session/
              - name: GF_AUTH_OAUTH_AUTO_LOGIN
                value: "false"
              - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
                value: "contains(groups[*], 'authentik Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"

    service:
      app:
        controller: teslamate-grafana
        ports:
          http:
            port: 3000

    persistence:
      data:
        enabled: true
        existingClaim: teslamate-grafana-pvc
        globalMounts:
          - path: /var/lib/grafana
