apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  dependsOn:
    - name: teslamate-mosquitto
      namespace: productivity
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: productivity
  values:
    controllers:
      teslamate:
        containers:
          app:
            image:
              repository: teslamate/teslamate
              tag: "2.2.0"
            env:
              - name: DATABASE_HOST
                value: teslamate-database-rw.productivity.svc.cluster.local
              - name: DATABASE_NAME
                value: teslamate
              - name: DATABASE_USER
                value: teslamate
              - name: DATABASE_PASS
                valueFrom:
                  secretKeyRef:
                    name: teslamate-database-app
                    key: password
              - name: ENCRYPTION_KEY
                valueFrom:
                  secretKeyRef:
                    name: teslamate-secrets
                    key: ENCRYPTION_KEY
              - name: MQTT_HOST
                value: teslamate-mosquitto.productivity.svc.cluster.local

    service:
      app:
        controller: teslamate
        ports:
          http:
            port: 4000

    persistence:
      import:
        enabled: true
        existingClaim: teslamate-import-pvc
        globalMounts:
          - path: /opt/app/import
