apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.zech.dev`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
      middlewares:
        - name: authentik
          namespace: traefik
