apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      prowlarr:
        containers:
          app:
            image:
              repository: linuxserver/prowlarr
              tag: "1.37.0"

            env:
              TZ: "Europe/Vienna"
              PUID: "1000"
              PGID: "1000"
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses

    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: 9696

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-pvc
        globalMounts:
          - path: /config
