apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: "1.18.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 5m
  releaseName: cert-manager
  targetNamespace: cert-manager
  install:
    remediation:
      remediateLastFailure: true
    crds: CreateReplace
  upgrade:
    remediation:
      remediateLastFailure: true
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
