apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  authentication:
    kubernetesAuth:
      identityId: "$(INFISICAL_IDENTITY_ID)"
      secretsScope:
        envSlug: production
        secretsPath: "/Proxmox-CSI"
