apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: kube-prometheus-stack-grafana-secrets
  namespace: monitoring
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Monitoring/Grafana"
  managedKubeSecretReferences:
    - secretName: kube-prometheus-stack-grafana-secrets
      secretNamespace: monitoring
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          admin-user: "{{ .ADMIN_USER.Value }}"
          admin-password: "{{ .ADMIN_PASSWORD.Value }}"
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .OAUTH_CLIENT_ID.Value }}"
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .OAUTH_CLIENT_SECRET.Value }}"
