apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infisical-secret-alertmanager.yaml
  - infisical-secret-grafana.yaml
  - prometheus-local-certificate.yaml
  - release.yaml
  - ingress.yaml
