apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Proxmox-CSI"
  managedKubeSecretReferences:
    - secretName: proxmox-csi-plugin
      secretNamespace: csi-proxmox
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        data:
          config.yaml: |
            clusters:
            - url: "https://pve.local.zech.co:8006/api2/json"
              insecure: false
              token_id: "{{ .PROXMOX_API_TOKEN_ID.Value }}"
              token_secret: "{{ .PROXMOX_API_TOKEN_SECRET.Value }}"
              region: "pve"
