apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - cloudflare-api-token-secret.yaml
  - tls-store.yaml
  - dashboard-ingress.yaml
  - authentik-middleware.yaml
