apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.zech.dev`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
      middlewares:
        - name: authentik
          namespace: traefik
