apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: traefik
      version: "36.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 5m
  releaseName: traefik
  targetNamespace: traefik
  install:
    remediation:
      remediateLastFailure: true
    crds: CreateReplace
  upgrade:
    remediation:
      remediateLastFailure: true
    crds: CreateReplace
  values:
    additionalArguments:
      - "--global.sendanonymoususage=false"
      - "--serverstransport.insecureskipverify=true"

    deployment:
      enabled: true
      replicas: 2
      podDisruptionBudget:
        enabled: true
        maxUnavailable: 1

    ports:
      web:
        port: 8000
        exposedPort: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        exposedPort: 443

    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: false

    rbac:
      enabled: true
      namespaced: false

    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: "10.0.20.100"
      spec:
        externalTrafficPolicy: Local

    logs:
      general:
        level: DEBUG
      access:
        enabled: true

    api:
      dashboard: true
      debug: false

    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 150Mi

    securityContext:
      capabilities:
        drop: [ ALL ]
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532

    podSecurityContext:
      fsGroup: 65532
