apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: speedtest-tracker-secrets
  namespace: monitoring
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Speedtest-Tracker"
  managedKubeSecretReferences:
    - secretName: speedtest-tracker-secrets
      secretNamespace: monitoring
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          APP_KEY: "{{ .APP_KEY.Value }}"
          MAIL_HOST: "{{ .MAIL_HOST.Value }}"
          MAIL_PORT: "{{ .MAIL_PORT.Value }}"
          MAIL_USERNAME: "{{ .MAIL_USERNAME.Value }}"
          MAIL_PASSWORD: "{{ .MAIL_PASSWORD.Value }}"
          MAIL_ENCRYPTION: "{{ .MAIL_ENCRYPTION.Value }}"
          MAIL_FROM_ADDRESS: "{{ .MAIL_FROM_ADDRESS.Value }}"
          MAIL_FROM_NAME: "{{ .MAIL_FROM_NAME.Value }}"
