apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: collabora-secrets
  namespace: cloud
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Nextcloud"
  managedKubeSecretReferences:
    - secretName: collabora-secrets
      secretNamespace: cloud
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          username: "{{ .COLLABORA_ADMIN_USERNAME.Value }}"
          password: "{{ .COLLABORA_ADMIN_PASSWORD.Value }}"
