apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collabora
  namespace: cloud
spec:
  interval: 15m
  timeout: 15m
  valuesFrom:
    - kind: Secret
      name: collabora-secrets
      valuesKey: username
      targetPath: collabora.username
      optional: false
    - kind: Secret
      name: collabora-secrets
      valuesKey: password
      targetPath: collabora.password
      optional: false
  chart:
    spec:
      chart: collabora-online
      version: "1.1.57"
      sourceRef:
        kind: HelmRepository
        name: collabora-online
        namespace: cloud
  values:
    fullnameOverride: collabora

    ingress:
      enabled: false

    collabora:
      server_name: office.${DOMAIN}
      aliasgroups:
        - host: https://cloud.${DOMAIN}
      dictionaries:
        - de_DE
        - en_GB
        - en_US
      extra_params: >-
        --o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false
