apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  namespace: auth
spec:
  instances: 3

  storage:
    size: 5Gi
    storageClass: "proxmox-csi"

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
