apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data-pvc
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: proxmox-csi
