apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: authentik
      version: "2026.2.0"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: auth
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secret-key
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
      optional: false

    - kind: Secret
      name: authentik-database-app
      valuesKey: password
      targetPath: authentik.postgresql.password
      optional: false

    - kind: Secret
      name: authentik-email-credentials
      valuesKey: AUTHENTIK_EMAIL_USERNAME
      targetPath: email.username

    - kind: Secret
      name: authentik-email-credentials
      valuesKey: AUTHENTIK_EMAIL_PASSWORD
      targetPath: email.password

  values:
    server:
      deploymentStrategy:
        type: Recreate
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containerSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: authentik-data-pvc
      volumeMounts:
        - name: data
          mountPath: /data
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      livenessProbe:
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 5
      readinessProbe:
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 5
      startupProbe:
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 60
      service:
        main:
          enabled: true
          type: ClusterIP
          ports:
            http:
              port: 80
              targetPort: 9000
              protocol: TCP

    worker:
      deploymentStrategy:
        type: Recreate
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containerSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: authentik-data-pvc
      volumeMounts:
        - name: data
          mountPath: /data
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      livenessProbe:
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 5
      readinessProbe:
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 5
      startupProbe:
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 60

    authentik:
      env:
        - name: AUTHENTIK_HOST
          value: https://sso.${DOMAIN}

      error_reporting:
        enabled: true

      postgresql:
        host: authentik-database-rw.auth.svc.cluster.local
        user: authentik
        database: authentik

    postgresql:
      enabled: false

    redis:
      enabled: true

    email:
      host: "smtp.eu.mailgun.org"
      port: 587
      use_tls: true
      use_ssl: false
      timeout: 15m
      from: "sso@zech.co"
