apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      sabnzbd:
        initContainers:
          host-whitelist:
            image:
              repository: alpine
              tag: "3.21.3"
            command:
              - /bin/sh
              - -ec
              - |
                file="/config/sabnzbd.ini"
                whitelist="localhost,127.0.0.1,sabnzbd.${DOMAIN}"

                if [ ! -f "$file" ]; then
                  echo "sabnzbd.ini not found at $file; skipping host_whitelist patch"
                  exit 0
                fi

                if grep -qE '^host_whitelist[[:space:]]*=' "$file"; then
                  sed -i "s|^host_whitelist[[:space:]]*=.*|host_whitelist = ${whitelist}|" "$file"
                else
                  printf '\nhost_whitelist = %s\n' "$whitelist" >> "$file"
                fi

        containers:
          app:
            image:
              repository: linuxserver/sabnzbd
              tag: "4.5.5"

            env:
              TZ: "Europe/Vienna"
              PUID: "1000"
              PGID: "1000"

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-pvc
        globalMounts:
          - path: /config

      media-downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-media-downloads-pvc
        globalMounts:
          - path: /downloads
