apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: media
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      protocol: TCP
      port: 8989
      targetPort: http
