apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: media
  values:
    controllers:
      sonarr:
        containers:
          app:
            image:
              repository: linuxserver/sonarr
              tag: "4.0.15"

            env:
              TZ: "Europe/Vienna"
              PUID: "1000"
              PGID: "1000"
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses

    service:
      app:
        controller: sonarr
        ports:
          http:
            port: 8989

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-pvc
        globalMounts:
          - path: /config

      media-tv:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-media-tv-pvc
        globalMounts:
          - path: /tv

      media-downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-media-downloads-pvc
        globalMounts:
          - path: /downloads
