apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:4.0.15
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Vienna"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: media-tv
              mountPath: /tv
            - name: media-downloads
              mountPath: /downloads
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: media-tv
          persistentVolumeClaim:
            claimName: nfs-media-tv-pvc
        - name: media-downloads
          persistentVolumeClaim:
            claimName: nfs-media-downloads-pvc
