apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: authentik-secret-key
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: kubernetes/production/authentik
        property: AUTHENTIK_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-email-credentials
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: authentik-email-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kubernetes/production/authentik
        property: email_username
    - secretKey: password
      remoteRef:
        key: kubernetes/production/authentik
        property: email_password
