apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik-secrets
  namespace: auth
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
        identityId: "$(INFISICAL_IDENTITY_ID)"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "$(INFISICAL_PROJECT_ID)"
        envSlug: production
        secretsPath: "/Authentik"
  managedKubeSecretReferences:
    - secretName: authentik-secret-key
      secretNamespace: auth
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY.Value }}"
    - secretName: authentik-email-credentials
      secretNamespace: auth
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          AUTHENTIK_EMAIL_USERNAME: "{{ .AUTHENTIK_EMAIL_USERNAME.Value }}"
          AUTHENTIK_EMAIL_PASSWORD: "{{ .AUTHENTIK_EMAIL_PASSWORD.Value }}"
