apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmk
  namespace: checkmk
spec:
  interval: 15m
  chart:
    spec:
      chart: checkmk
      version: "1.7.0"
      sourceRef:
        kind: HelmRepository
        name: checkmk
        namespace: checkmk
      interval: 5m
  releaseName: checkmk
  targetNamespace: checkmk
  dependsOn:
    - name: traefik
      namespace: traefik
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    clusterCollector:
      service:
        type: ClusterIP

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
