apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: karakeep-secrets
  namespace: productivity
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Karakeep"
  managedKubeSecretReferences:
    - secretName: karakeep-secrets
      secretNamespace: productivity
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET.Value }}"
          MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY.Value }}"
          OAUTH_CLIENT_ID: "{{ .OAUTH_CLIENT_ID.Value }}"
          OAUTH_CLIENT_SECRET: "{{ .OAUTH_CLIENT_SECRET.Value }}"
          OPENAI_API_KEY: "{{ .OPENAI_API_KEY.Value }}"
