apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  dependsOn:
    - name: karakeep-chrome
      namespace: productivity
    - name: karakeep-meilisearch
      namespace: productivity
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-productivity
        namespace: productivity
  values:
    controllers:
      karakeep:
        pod:
          hostAliases:
            - ip: "${TRAEFIK_LB_IP}"
              hostnames:
                - "sso.${DOMAIN}"
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: "0.30.0"
            resources:
              requests:
                cpu: 200m
                memory: 384Mi
              limits:
                cpu: "1"
                memory: 1Gi
            env:
              - name: DATA_DIR
                value: /data
              - name: NEXTAUTH_URL
                value: "https://karakeep.${DOMAIN}"
              - name: NEXTAUTH_SECRET
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secrets
                    key: NEXTAUTH_SECRET
              - name: MEILI_ADDR
                value: http://karakeep-meilisearch.productivity.svc.cluster.local:7700
              - name: MEILI_MASTER_KEY
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secrets
                    key: MEILI_MASTER_KEY
              - name: BROWSER_WEB_URL
                value: http://karakeep-chrome.productivity.svc.cluster.local:9222
              - name: DISABLE_SIGNUPS
                value: "true"
              - name: OAUTH_WELLKNOWN_URL
                value: "https://sso.${DOMAIN}/application/o/karakeep/.well-known/openid-configuration"
              - name: OAUTH_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secrets
                    key: OAUTH_CLIENT_ID
              - name: OAUTH_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secrets
                    key: OAUTH_CLIENT_SECRET
              - name: OAUTH_SCOPE
                value: "openid email profile"
              - name: OAUTH_PROVIDER_NAME
                value: Authentik
              - name: OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING
                value: "true"
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secrets
                    key: OPENAI_API_KEY

    service:
      app:
        controller: karakeep
        ports:
          http:
            port: 3000

    persistence:
      data:
        enabled: true
        existingClaim: karakeep-data-pvc
        globalMounts:
          - path: /data
