apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: freshrss-database
  namespace: productivity
spec:
  instances: 1

  storage:
    size: 1Gi
    storageClass: "proxmox-csi"

  bootstrap:
    initdb:
      database: freshrss
      owner: freshrss
