apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m
  path: ./applications/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
      namespace: flux-system
    - name: infrastructure-configs
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
