---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-vars
    - name: prod-core-traefik-config
    - name: prod-core-cert-manager-config
    - name: prod-core-proxmox-csi-config
    - name: prod-core-cnpg-controller
    - name: prod-base
  interval: 10m
  retryInterval: 1m
  path: ./apps/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
  wait: true
  timeout: 30m
