# clusters/production/base.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: core-longhorn-release # Hängt nur vom Longhorn Controller ab, nicht von seiner Config
  interval: 10m
  path: ./clusters/production/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
