---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: core-longhorn
  interval: 10m
  path: ./clusters/production/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
