apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
      namespace: flux-system
  interval: 10m
  path: ./base/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
