---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-longhorn
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: core-metallb
  interval: 10m
  path: ./clusters/production/core/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: core-metallb
    - name: core-cert-manager
  interval: 10m
  path: ./clusters/production/core/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cnpg
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/cnpg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-checkmk
  namespace: flux-system
spec:
  dependsOn:
    - name: core-traefik
  interval: 10m
  path: ./clusters/production/core/checkmk
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
