---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-longhorn-release
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/longhorn/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metallb-release
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/metallb/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager-release
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/cert-manager/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-traefik-release
  namespace: flux-system
spec:
  dependsOn:
    - name: core-metallb-release
    - name: core-cert-manager-release
  interval: 10m
  path: ./clusters/production/core/traefik/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cnpg-release
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/cnpg/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-checkmk-release
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/core/checkmk/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-metallb-release
  interval: 10m
  path: ./clusters/production/core/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-cert-manager-release
  interval: 10m
  path: ./clusters/production/core/cert-manager/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-traefik-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-traefik-release
  interval: 10m
  path: ./clusters/production/core/traefik/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-longhorn-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-longhorn-release
    - name: core-traefik-release
  interval: 10m
  path: ./clusters/production/core/longhorn/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-checkmk-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-checkmk-release
    - name: core-traefik-release
  interval: 10m
  path: ./clusters/production/core/checkmk/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
