apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-base
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-coredns-config
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-base
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/coredns/base/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-infisical-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-base
  interval: 10m
  retryInterval: 1m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: infisical-secrets-operator
      namespace: infisical
  path: ./infrastructure/infisical-operator/base/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-proxmox-csi-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-vars
    - name: prod-base
    - name: prod-core-infisical-operator
  interval: 10m
  retryInterval: 1m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: proxmox-csi-plugin
      namespace: csi-proxmox
  path: ./infrastructure/proxmox-csi/base/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-metallb-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-base
  interval: 10m
  retryInterval: 1m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
  path: ./infrastructure/metallb/base/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-cert-manager-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-base
  interval: 10m
  retryInterval: 1m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  path: ./infrastructure/cert-manager/base/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-traefik-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-vars
    - name: prod-base
    - name: prod-core-metallb-controller
    - name: prod-core-cert-manager-controller
  interval: 10m
  retryInterval: 1m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: traefik
      namespace: traefik
  path: ./infrastructure/traefik/base/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-cnpg-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-base
  interval: 10m
  retryInterval: 1m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudnative-pg
      namespace: cnpg-system
  path: ./infrastructure/cnpg/base/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-metrics-server-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-base
  interval: 10m
  retryInterval: 1m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metrics-server
      namespace: kube-system
  path: ./infrastructure/metrics-server/base/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-vars
    - name: prod-core-metallb-controller
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/metallb/base/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-vars
    - name: prod-core-cert-manager-controller
    - name: prod-core-traefik-controller
    - name: prod-core-infisical-operator
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/cert-manager/base/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-traefik-config
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-vars
    - name: prod-core-traefik-controller
    - name: prod-core-cert-manager-config
    - name: prod-core-infisical-operator
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/traefik/base/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-core-proxmox-csi-config
  namespace: flux-system
spec:
  dependsOn:
    - name: prod-core-proxmox-csi-controller
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/proxmox-csi/base/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
