apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn-release
  interval: 10m
  path: ./infrastructure/production/longhorn/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
