apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/production/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
