apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-release
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/production/metallb/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system
  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/hostNetwork
          value: true
      target:
        kind: Deployment
        name: metallb-controller
        namespace: metallb-system
