apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-config
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-release
  interval: 10m
  path: ./infrastructure/production/traefik/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  decryption:
    provider: sops
    secretRef:
      name: sops-age
