apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: traefik
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:JjJ9ZMuVf+T+51KonSKyt3QOKb7Dgo6zbuMakSGYd/BUI5uLoIzboA==,iv:TEEuZC+TMLdUjhO6AAMuj66bitc5HyfHCl+tzBiWLdY=,tag:/4N8MLhx61Q978JwHwfOqQ==,type:str]
sops:
    age:
        - recipient: age14d2euuz2athvse6rr8k3pl2acdlxnq7tld5l8ps5tvszq439ne2qyue8ft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR0hVUlBDTE5EMFc3Y2NN
            c1NpZ1ZzbXBHN2lCTlJUcFc5ZmV3aFBEWkFVCnBLeXRLS2hZM0NDV1VWOWdIbkYw
            VForRXczdTB2VnhSUEpXWUdwUG14T0kKLS0tIEIvTFA1VUc3aG04V281dllBQnc5
            QnprcGlOODRyUEc5WlJPOExpd0JzSFEKdlwWl7rrsYp2tB/W4CvrXVhA0AZ/osF3
            sCQF0sWPAWUeTsUHbYkiN/yT+bppz/Ei+ajU/+oyTh3Waa74GD9dSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T18:26:40Z"
    mac: ENC[AES256_GCM,data:6W3FbIP/f/daXYPt9Eu0sHlty0kxiavdFhlNKVUFqHmTyBSI0OqwIUzuwxEsC4M+M6NS/Q7eanp+xIP3gZBdMnWdUoose9w+iQFzF3lT6VyRdD6yT8UwnLf/U1+4s7NjmvNhrOg2CM+PLznmZZvVhWCxnx1WenID69i1E+dLXFg=,iv:RYmFXCcFsKPElknwYkNXrzGUy0yt/WpwiCBT/0qsfTc=,tag:+ImVomHNUVptw+91IZDGiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
