apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Nextcloud"
  managedKubeSecretReferences:
    - secretName: nextcloud-secrets
      secretNamespace: nextcloud
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          nextcloud-username: "{{ .NEXTCLOUD_ADMIN_USER.Value }}"
          nextcloud-password: "{{ .NEXTCLOUD_ADMIN_PASSWORD.Value }}"
          nextcloud-token: "{{ .NEXTCLOUD_INSTANCE_TOKEN.Value }}"
