apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: cloud
spec:
  interval: 15m
  timeout: 20m
  dependsOn:
    - name: collabora
      namespace: cloud
  chart:
    spec:
      chart: nextcloud
      version: "8.9.1"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: cloud
  values:
    fullnameOverride: nextcloud
    replicaCount: 1

    autoscaling:
      enabled: false

    image:
      tag: "32.0.6"

    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 60

    livenessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6

    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 12

    ingress:
      enabled: false

    internalDatabase:
      enabled: false

    mariadb:
      enabled: false

    redis:
      enabled: true

    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-database-rw.cloud.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-database-app
        usernameKey: username
        passwordKey: password

    persistence:
      enabled: true
      existingClaim: nfs-cloud-data-pvc

    nextcloud:
      host: cloud.${DOMAIN}
      datadir: /var/www/html/data
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        tokenKey: nextcloud-token
      configs:
        z-nextcloud-config.config.php: |
          <?php
          $CONFIG = array (
            'trusted_domains' =>
            array (
              0 => 'cloud.${DOMAIN}',
            ),
            'overwrite.cli.url' => 'https://cloud.${DOMAIN}',
            'overwriteprotocol' => 'https',
            'default_phone_region' => 'AT',
          );
    collabora:
      enabled: false
