apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-security-headers
  namespace: nextcloud
spec:
  headers:
    stsSeconds: 15552000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
