apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "36.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 5m
  releaseName: traefik
  targetNamespace: traefik
  install:
    remediation:
      remediateLastFailure: true
    crds: CreateReplace
  upgrade:
    remediation:
      remediateLastFailure: true
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
