---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: dev-vars
    - name: dev-core-traefik-config
    - name: dev-core-cert-manager-config
    - name: dev-core-proxmox-csi-config
    - name: dev-core-cnpg-controller
    - name: dev-base
  interval: 10m
  retryInterval: 1m
  path: ./apps/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-vars
  wait: true
  timeout: 30m
