---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-vars
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  path: ./clusters/development/vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
