apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - issuer-secret.yaml
  - issuer.yaml
  - wildcard-certificate.yaml
