apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data-pvc
  namespace: finance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: proxmox-csi
