apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseerr.zech.dev`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
