apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-secrets-operator
  namespace: infisical
spec:
  interval: 15m
  chart:
    spec:
      chart: secrets-operator
      version: "0.11.3"
      sourceRef:
        kind: HelmRepository
        name: infisical-helm-charts
        namespace: infisical
      interval: 5m
  releaseName: infisical-secrets-operator
  targetNamespace: infisical
  values:
    controllerManager:
      manager:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
