apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-secrets-operator
  namespace: infisical
spec:
  interval: 15m
  chart:
    spec:
      chart: secrets-operator
      version: "0.10.23"
      sourceRef:
        kind: HelmRepository
        name: infisical-helm-charts
        namespace: infisical
      interval: 5m
  releaseName: infisical-secrets-operator
  targetNamespace: infisical
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
