apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-service-account
  namespace: infisical
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-token-reviewer
  namespace: infisical
