apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jellystat-database
  namespace: media
spec:
  instances: 1
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: "1"
      memory: 1Gi

  storage:
    size: 2Gi
    storageClass: "proxmox-csi"

  bootstrap:
    initdb:
      database: jellystat
      owner: jellystat
