apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jellystat-database
  namespace: media
spec:
  instances: 1

  storage:
    size: 2Gi
    storageClass: "proxmox-csi"

  bootstrap:
    initdb:
      database: jellystat
      owner: jellystat
