apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellystat
  namespace: media
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      jellystat:
        containers:
          app:
            image:
              repository: cyfershepard/jellystat
              tag: "1.1.8"

            env:
              - name: DB
                value: postgres
              - name: POSTGRES_IP
                value: jellystat-database-rw.media.svc.cluster.local
              - name: POSTGRES_PORT
                value: "5432"
              - name: POSTGRES_USER
                value: jellystat
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jellystat-database-app
                    key: password
              - name: POSTGRES_DB
                value: jellystat
              - name: JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: jellystat-secrets
                    key: JWT_SECRET

    service:
      app:
        controller: jellystat
        ports:
          http:
            port: 3000

    persistence:
      config:
        enabled: true
        existingClaim: jellystat-backup-data-pvc
        globalMounts:
          - path: /app/backend/backup-data
