apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-database
  namespace: productivity
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  instances: 1
  storage:
    size: 5Gi
    storageClass: "proxmox-csi"
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
