apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: paperless-secrets
  namespace: productivity
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Paperless"
  managedKubeSecretReferences:
    - secretName: paperless-secrets
      secretNamespace: productivity
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY.Value }}"
          PAPERLESS_SOCIALACCOUNT_PROVIDERS: "{{ .PAPERLESS_SOCIALACCOUNT_PROVIDERS.Value }}"
