apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-gotenberg
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-productivity
        namespace: productivity
  values:
    controllers:
      paperless-gotenberg:
        containers:
          app:
            image:
              repository: gotenberg/gotenberg
              tag: "8.27.0"
            args:
              - gotenberg
              - --chromium-disable-javascript=true
              - --chromium-allow-list=file:///tmp/.*
    service:
      app:
        controller: paperless-gotenberg
        ports:
          http:
            port: 3000
