apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-tika
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-productivity
        namespace: productivity
  values:
    controllers:
      paperless-tika:
        containers:
          app:
            image:
              repository: apache/tika
              tag: "3.2.3.0"
    service:
      app:
        controller: paperless-tika
        ports:
          http:
            port: 9998
