apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-productivity
        namespace: productivity
  values:
    controllers:
      paperless-redis:
        containers:
          app:
            image:
              repository: redis
              tag: "8.6.1-alpine"
            command:
              - redis-server
              - --appendonly
              - "yes"
    service:
      app:
        controller: paperless-redis
        ports:
          redis:
            port: 6379
    persistence:
      data:
        enabled: true
        existingClaim: paperless-redis-pvc
        globalMounts:
          - path: /data
