apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress
  namespace: auth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sso.zech.dev`)
      kind: Rule
      services:
        - name: authentik-server
          port: http
