apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.zech.dev`)
      kind: Rule
      services:
        - name: bazarr
          port: 6767
      middlewares:
        - name: authentik
          namespace: traefik
