apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      bazarr:
        containers:
          app:
            image:
              repository: linuxserver/bazarr
              tag: "1.5.2"

            env:
              TZ: "Europe/Vienna"
              PUID: "1000"
              PGID: "1000"

    service:
      app:
        controller: bazarr
        ports:
          http:
            port: 6767

    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-pvc
        globalMounts:
          - path: /config

      media-tv:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-media-tv-pvc
        globalMounts:
          - path: /tv

      media-downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-media-movies-pvc
        globalMounts:
          - path: /movies
