apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: authentik
      version: "2025.6.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 5m
  values:
    authentik:
      secret_key:
        secretName: authentik-secret-key
        secretKey: AUTHENTIK_SECRET_KEY
        
      error_reporting:
        enabled: true

      postgresql:
        host: authentik-database-rw.authentik.svc.cluster.local
        user: file:///authentik-database-credentials/username
        password: file:///authentik-database-credentials/password
        database: file:///authentik-database-credentials/dbname

    postgresql:
      enabled: false

    persistence:
      enabled: true
      storageClass: "longhorn"

    server:
      volumes:
        - name: authentik-database-credentials
          secret:
            secretName: authentik-database-authentik
      volumeMounts:
        - name: authentik-database-credentials
          mountPath: /authentik-database-credentials
          readOnly: true

    worker:
      volumes:
        - name: authentik-database-credentials
          secret:
            secretName: authentik-database-authentik
      volumeMounts:
        - name: authentik-database-credentials
          mountPath: /authentik-database-credentials
          readOnly: true
