apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: authentik
      version: "2025.6.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik-secret-key
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
      optional: true

    - kind: Secret
      name: authentik-database-authentik
      valuesKey: password
      targetPath: authentik.postgresql.password
      optional: true

  values:
    authentik:
      error_reporting:
        enabled: true

      postgresql:
        host: authentik-database-rw.authentik.svc.cluster.local
        user: authentik
        database: authentik

    postgresql:
      enabled: false
