apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: "2025.6.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 5m
  values:
    authentik:
      secret_key:
        secretName: authentik-secret-key
        secretKey: AUTHENTIK_SECRET_KEY
      error_reporting:
        enabled: true

      postgresql:
        host: authentik-database-rw.authentik.svc.cluster.local

        user:
          valueFrom:
            secretKeyRef:
              name: authentik-database-authentik
              key: username
        database:
          valueFrom:
            secretKeyRef:
              name: authentik-database-authentik
              key: dbname
        password:
          valueFrom:
            secretKeyRef:
              name: authentik-database-authentik
              key: password

    postgresql:
      enabled: false

    persistence:
      enabled: true
      storageClass: "longhorn"
