apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: "2025.6.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 5m
  values:
    authentik:
      secret_key:
        secretName: authentik-secret-key
        secretKey: AUTHENTIK_SECRET_KEY
      error_reporting:
        enabled: true

    ingress:
      enabled: false

    # For simplicity, we use the bundled PostgreSQL.
    # For production, an external database is recommended.
    postgresql:
      enabled: true

    # Enable persistence and use Longhorn for storage.
    persistence:
      enabled: true
      storageClass: "longhorn"
