apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-namespace.yaml
  - authentik-repository.yaml
  - authentik-secrets.yaml
  - authentik-release.yaml
  - authentik-ingress.yaml
