apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd-ingress
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sabnzbd.zech.dev`)
      kind: Rule
      services:
        - name: sabnzbd
          port: 8080
      middlewares:
        - name: authentik
          namespace: traefik
