apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.1.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      sabnzbd:
        containers:
          app:
            image:
              repository: linuxserver/sabnzbd
              tag: "4.5.2"

            env:
              TZ: "Europe/Vienna"
              PUID: "1000"
              PGID: "1000"

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-pvc
        globalMounts:
          - path: /config

      media-downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-media-downloads-pvc
        globalMounts:
          - path: /downloads
