apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: pulse-agent-secrets
  namespace: monitoring
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Pulse"
  managedKubeSecretReferences:
    - secretName: pulse-agent-secrets
      secretNamespace: monitoring
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          PULSE_TOKEN: "{{ .PULSE_TOKEN.Value }}"
