apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-resources
  namespace: cnpg-system
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 200m
        memory: 256Mi
      default:
        cpu: "1"
        memory: 1Gi
