apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-resources
  namespace: media
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 1Gi
