apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18-0.4.3
  instances: 1
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: "1"
      memory: 1Gi
  storage:
    size: 5Gi
    storageClass: "proxmox-csi"
  bootstrap:
    initdb:
      database: immich
      owner: immich
