apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: immich
      version: "0.10.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
  values:
    valkey:
      enabled: true

    immich:
      persistence:
        library:
          existingClaim: nfs-immich-library-pvc
        upload:
          existingClaim: nfs-immich-uploads-pvc
        thumbs:
          existingClaim: nfs-immich-thumbnails-pvc
        profile:
          existingClaim: nfs-immich-profile-pvc
        video:
          existingClaim: nfs-immich-videos-pvc
        backups:
          existingClaim: nfs-immich-backups-pvc
        machine-learning:
          existingClaim: nfs-immich-machine-learning-pvc

    env:
      - name: TZ
        value: Europe/Vienna
      - name: DB_HOSTNAME
        value: immich-database-rw.immich.svc.cluster.local
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: immich-database-app
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: immich-database-app
            key: password
      - name: DB_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: immich-database-app
            key: dbname
      - name: DB_VECTOR_EXTENSION
        value: vchord

    ingress:
      main:
        enabled: true
        className: traefik
        hosts:
          - host: photos.${DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: wildcard-domain-tls
            hosts:
              - photos.${DOMAIN}
