apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
  namespace: monitoring
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-monitoring
        namespace: monitoring
  values:
    controllers:
      changedetection:
        containers:
          app:
            image:
              repository: linuxserver/changedetection.io
              tag: "0.53.5"
            env:
              - name: TZ
                value: Europe/Vienna
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
    service:
      app:
        controller: changedetection
        ports:
          http:
            port: 5000
    persistence:
      config:
        enabled: true
        existingClaim: changedetection-config-pvc
        globalMounts:
          - path: /config
