apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: norish-secrets
  namespace: health
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Norish"
  managedKubeSecretReferences:
    - secretName: norish-secrets
      secretNamespace: health
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          MASTER_KEY: "{{ .MASTER_KEY.Value }}"
          OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID.Value }}"
          OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET.Value }}"
