---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: norish-uploads-pvc
  namespace: health
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: proxmox-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: norish-redis-pvc
  namespace: health
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: proxmox-csi
