apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: norish-redis
  namespace: health
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-health
        namespace: health
  values:
    controllers:
      norish-redis:
        containers:
          app:
            image:
              repository: redis
              tag: "8.4.1"
            command:
              - redis-server
              - --appendonly
              - "yes"
    service:
      app:
        controller: norish-redis
        ports:
          redis:
            port: 6379
    persistence:
      data:
        enabled: true
        existingClaim: norish-redis-pvc
        globalMounts:
          - path: /data
