apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: norish-chrome-headless
  namespace: health
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-health
        namespace: health
  values:
    controllers:
      norish-chrome-headless:
        containers:
          app:
            image:
              repository: zenika/alpine-chrome
              tag: "latest"
            args:
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=3000
              - --headless
    service:
      app:
        controller: norish-chrome-headless
        ports:
          http:
            port: 3000
