apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: media
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-media
        namespace: media
  values:
    controllers:
      seerr:
        containers:
          app:
            image:
              repository: seerr/seerr
              tag: "v3.0.1"

            env:
              TZ: "Europe/Vienna"

    service:
      app:
        controller: seerr
        ports:
          http:
            port: 5055

    persistence:
      config:
        enabled: true
        existingClaim: seerr-config-pvc
        globalMounts:
          - path: /app/config
