apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: n8n-secrets
  namespace: automation
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/n8n"
  managedKubeSecretReferences:
    - secretName: n8n-secrets
      secretNamespace: automation
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          N8N_BASIC_AUTH_USER: "{{ .N8N_BASIC_AUTH_USER.Value }}"
          N8N_BASIC_AUTH_PASSWORD: "{{ .N8N_BASIC_AUTH_PASSWORD.Value }}"
          N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY.Value }}"
