apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: automation
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-automation
        namespace: automation
  values:
    controllers:
      n8n:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: n8nio/n8n
              tag: "2.8.2"
            env:
              - name: DB_TYPE
                value: postgresdb
              - name: DB_POSTGRESDB_HOST
                value: n8n-database-rw.automation.svc.cluster.local
              - name: DB_POSTGRESDB_PORT
                value: "5432"
              - name: DB_POSTGRESDB_DATABASE
                value: n8n
              - name: DB_POSTGRESDB_USER
                value: n8n
              - name: DB_POSTGRESDB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: n8n-database-app
                    key: password
              - name: N8N_BASIC_AUTH_ACTIVE
                value: "true"
              - name: N8N_BASIC_AUTH_USER
                valueFrom:
                  secretKeyRef:
                    name: n8n-secrets
                    key: N8N_BASIC_AUTH_USER
              - name: N8N_BASIC_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: n8n-secrets
                    key: N8N_BASIC_AUTH_PASSWORD
              - name: N8N_HOST
                value: n8n.${DOMAIN}
              - name: N8N_PORT
                value: "5678"
              - name: N8N_PROTOCOL
                value: https
              - name: NODE_ENV
                value: production
              - name: WEBHOOK_URL
                value: https://n8n.${DOMAIN}
              - name: N8N_EDITOR_BASE_URL
                value: https://n8n.${DOMAIN}
              - name: GENERIC_TIMEZONE
                value: Europe/Vienna
              - name: N8N_DIAGNOSTICS_ENABLED
                value: "false"
              - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
                value: "true"
              - name: N8N_ENCRYPTION_KEY
                valueFrom:
                  secretKeyRef:
                    name: n8n-secrets
                    key: N8N_ENCRYPTION_KEY
    service:
      app:
        controller: n8n
        ports:
          http:
            port: 5678
    persistence:
      data:
        enabled: true
        existingClaim: n8n-data-pvc
        globalMounts:
          - path: /home/node/.n8n
