apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
  namespace: productivity
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts-productivity
        namespace: productivity
  values:
    controllers:
      bentopdf:
        containers:
          app:
            image:
              repository: ghcr.io/alam00000/bentopdf-simple
              tag: "2.4.0"

    service:
      app:
        controller: bentopdf
        ports:
          http:
            port: 8080
