apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: unifi-network-application-secrets
  namespace: unifi
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Unifi-Network-Application"
  managedKubeSecretReferences:
    - secretName: unifi-network-application-mongodb-env
      secretNamespace: unifi
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          MONGO_DBNAME: "{{ .MONGO_DBNAME.Value }}"
          MONGO_USER: "{{ .MONGO_USER.Value }}"
          MONGO_PASS: "{{ .MONGO_PASS.Value }}"
          MONGO_INITDB_ROOT_USERNAME: "{{ .MONGO_INITDB_ROOT_USERNAME.Value }}"
          MONGO_INITDB_ROOT_PASSWORD: "{{ .MONGO_INITDB_ROOT_PASSWORD.Value }}"
