---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-network-application-config-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: proxmox-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-network-application-mongodb-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi
