apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: healthchecks-secrets
  namespace: monitoring
spec:
  hostAPI: https://infisical.zech.co/api
  syncConfig:
    resyncInterval: 1h
  authentication:
    kubernetesAuth:
      identityId: "${INFISICAL_IDENTITY_ID}"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
      secretsScope:
        projectId: "${INFISICAL_PROJECT_ID}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/Healthchecks"
  managedKubeSecretReferences:
    - secretName: healthchecks-secrets
      secretNamespace: monitoring
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          SECRET_KEY: "{{ .SECRET_KEY.Value }}"
          EMAIL_HOST: "{{ .EMAIL_HOST.Value }}"
          EMAIL_HOST_USER: "{{ .EMAIL_HOST_USER.Value }}"
          EMAIL_HOST_PASSWORD: "{{ .EMAIL_HOST_PASSWORD.Value }}"
          DEFAULT_FROM_EMAIL: "{{ .DEFAULT_FROM_EMAIL.Value }}"
          SUPERUSER_EMAIL: "{{ .SUPERUSER_EMAIL.Value }}"
          SUPERUSER_PASSWORD: "{{ .SUPERUSER_PASSWORD.Value }}"
