apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthchecks-config-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: proxmox-csi
