apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: cnpg-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnativepg
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg
        namespace: cnpg-system
      interval: 5m
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    installCRDs: true
